FROM konas397/mygitdiff2fly:1.0
COPY run.sh /opt/app/
RUN chmod +x /opt/app/run.sh
COPY ./ /work
ARG release_repo
ARG release_version
echo "$release_repo"
echo "$release_version"
WORKDIR /work                      
RUN /opt/app/run.sh $release_repo $release_version
ENTRYPOINT [ "/bin/sh" ]